// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelAccommodationBooking.Config.Common.Persistence;

#nullable disable

namespace TravelAccommodationBooking.Config.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoomFeatureRoomType", b =>
                {
                    b.Property<Guid>("FeaturesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoomTypesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FeaturesId", "RoomTypesId");

                    b.HasIndex("RoomTypesId");

                    b.ToTable("RoomFeatureRoomType");
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7d3155a2-95f8-4d9b-bc24-662ae053f1c9"),
                            BookingDate = new DateTime(2024, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInDate = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2024, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 100.0,
                            RoomId = new Guid("a98b8a9d-4c5a-4a90-a2d2-5f1441b93db6"),
                            UserId = new Guid("c6c45f7c-2dfe-4c1e-9a9b-8b173c71b32c")
                        },
                        new
                        {
                            Id = new Guid("efeb3d13-3dab-46c9-aa9a-9f22dd58e06e"),
                            BookingDate = new DateTime(2024, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2024, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 150.0,
                            RoomId = new Guid("4e1cb3d9-bc3b-4997-a3d5-0c56cf17fe7a"),
                            UserId = new Guid("aaf21a7d-8fc3-4c9f-8a8e-1eeec8dcd462")
                        },
                        new
                        {
                            Id = new Guid("0bf4a177-98b8-4f67-8a56-95669c320890"),
                            BookingDate = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckInDate = new DateTime(2024, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2024, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Price = 200.0,
                            RoomId = new Guid("c6898b7e-ee09-4b36-8b20-22e8c2a63e29"),
                            UserId = new Guid("f44c3eb4-2c8a-4a77-a31b-04c4619aa15a")
                        });
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.City", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CountryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PostOffice")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9e85d04-548c-4f98-afe9-2a8831c62a90"),
                            CountryCode = "US",
                            CountryName = "United States",
                            Name = "New York",
                            PostOffice = "NYC"
                        },
                        new
                        {
                            Id = new Guid("8d2aeb7a-7c67-4911-aa2c-d6a3b4dc7e9e"),
                            CountryCode = "UK",
                            CountryName = "United Kingdom",
                            Name = "London",
                            PostOffice = "LDN"
                        },
                        new
                        {
                            Id = new Guid("3c7e66f5-46a9-4b8d-8e90-85b5a9e2c2fd"),
                            CountryCode = "JP",
                            CountryName = "Japan",
                            Name = "Tokyo",
                            PostOffice = "TKY"
                        });
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.Discount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("DiscountPercentage")
                        .HasColumnType("real");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FloorsNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Hotels", t =>
                        {
                            t.HasCheckConstraint("CK_Hotel_RatingRange", "[Rating] >= 0 AND [Rating] <= 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("98c2c9fe-1a1c-4eaa-a7f5-b9d19b246c27"),
                            CityId = new Guid("f9e85d04-548c-4f98-afe9-2a8831c62a90"),
                            Description = "A luxurious hotel with top-notch amenities.",
                            FloorsNumber = 15,
                            Name = "Luxury HT",
                            OwnerId = new Guid("55b1aa11-12e7-4e0f-8425-67c1c1e62c2d"),
                            PhoneNumber = "0123456789",
                            Rating = 4.5f,
                            StreetAddress = "123 Main Street"
                        },
                        new
                        {
                            Id = new Guid("bfa4173d-7893-48b9-a497-5f4c7fb2492b"),
                            CityId = new Guid("8d2aeb7a-7c67-4911-aa2c-d6a3b4dc7e9e"),
                            Description = "A cozy lodge nestled in the heart of nature.",
                            FloorsNumber = 5,
                            Name = "Cozy Lodge",
                            OwnerId = new Guid("55b1aa11-12e7-4e0f-8425-67c1c1e62c2d"),
                            PhoneNumber = "2012345678",
                            Rating = 3.8f,
                            StreetAddress = "456 Oak Avenue"
                        },
                        new
                        {
                            Id = new Guid("9461e08b-92d3-45da-b6b3-efc0cfcc4a3a"),
                            CityId = new Guid("3c7e66f5-46a9-4b8d-8e90-85b5a9e2c2fd"),
                            Description = "A resort with breathtaking sunset views over the ocean.",
                            FloorsNumber = 10,
                            Name = "Sunset Resort",
                            OwnerId = new Guid("77b2c30b-65d0-4ea7-8a5e-71e7c294f117"),
                            PhoneNumber = "312345678",
                            Rating = 4.2f,
                            StreetAddress = "789 Beachfront Road"
                        });
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("Method");

                    b.HasIndex("Status");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f5cc9f0-796f-498d-9f3f-9e5249a4f6ae"),
                            Amount = 1500.0,
                            BookingId = new Guid("0bf4a177-98b8-4f67-8a56-95669c320890"),
                            Method = "CreditCard",
                            Status = "Paid"
                        },
                        new
                        {
                            Id = new Guid("1c8d70bd-2534-4991-bddf-84c7edee1a79"),
                            Amount = 1200.0,
                            BookingId = new Guid("efeb3d13-3dab-46c9-aa9a-9f22dd58e06e"),
                            Method = "Cash",
                            Status = "InProgress"
                        },
                        new
                        {
                            Id = new Guid("8f974636-4f53-48d9-af99-2f7f1d3e0474"),
                            Amount = 2000.0,
                            BookingId = new Guid("7d3155a2-95f8-4d9b-bc24-662ae053f1c9"),
                            Method = "Cash",
                            Status = "Cancelled"
                        });
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_RatingRange", "[Rating] >= 0 AND [Rating] <= 5");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("63e4bb25-28b1-4fc4-9b93-9254d94dab23"),
                            BookingId = new Guid("0bf4a177-98b8-4f67-8a56-95669c320890"),
                            Comment = "Excellent service and comfortable stay!",
                            Rating = 4.8f,
                            ReviewDate = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("85a5a0b4-0e04-4c46-b7ac-6cf609e4f2aa"),
                            BookingId = new Guid("efeb3d13-3dab-46c9-aa9a-9f22dd58e06e"),
                            Comment = "Friendly staff and great location.",
                            Rating = 4.5f,
                            ReviewDate = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("192045db-c6db-49c9-aa6b-2e3d6c7f3b79"),
                            BookingId = new Guid("7d3155a2-95f8-4d9b-bc24-662ae053f1c9"),
                            Comment = "Clean rooms and beautiful views.",
                            Rating = 4.2f,
                            ReviewDate = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Rooms.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AdultsCapacity")
                        .HasColumnType("int");

                    b.Property<int>("ChildrenCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("Rating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("real")
                        .HasDefaultValue(0f);

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("View")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("Rooms", t =>
                        {
                            t.HasCheckConstraint("CK_Review_RatingRange", "[Rating] >= 0 AND [Rating] <= 5")
                                .HasName("CK_Review_RatingRange1");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("a98b8a9d-4c5a-4a90-a2d2-5f1441b93db6"),
                            AdultsCapacity = 2,
                            ChildrenCapacity = 2,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Rating = 4.2f,
                            RoomTypeId = new Guid("5a5de3b8-3ed8-4f0a-bda9-cf73225a64a1"),
                            View = "City View"
                        },
                        new
                        {
                            Id = new Guid("4e1cb3d9-bc3b-4997-a3d5-0c56cf17fe7a"),
                            AdultsCapacity = 3,
                            ChildrenCapacity = 3,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Rating = 4.4f,
                            RoomTypeId = new Guid("d67ddbe4-1f1a-4d85-bcc1-ec3a475ecb68"),
                            View = "Ocean View"
                        },
                        new
                        {
                            Id = new Guid("c6898b7e-ee09-4b36-8b20-22e8c2a63e29"),
                            AdultsCapacity = 4,
                            ChildrenCapacity = 4,
                            HotelId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Rating = 4.8f,
                            RoomTypeId = new Guid("4b4c0ea5-0b9a-4a20-8ad9-77441fb912d2"),
                            View = "Mountain View"
                        });
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Rooms.RoomFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomFeatures");
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Rooms.RoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("PricePerNight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.ToTable("RoomTypes", t =>
                        {
                            t.HasCheckConstraint("CK_RoomType_PriceRange", "[PricePerNight] >= 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("5a5de3b8-3ed8-4f0a-bda9-cf73225a64a1"),
                            Category = "Single",
                            HotelId = new Guid("98c2c9fe-1a1c-4eaa-a7f5-b9d19b246c27"),
                            PricePerNight = 1000f
                        },
                        new
                        {
                            Id = new Guid("d67ddbe4-1f1a-4d85-bcc1-ec3a475ecb68"),
                            Category = "Double",
                            HotelId = new Guid("bfa4173d-7893-48b9-a497-5f4c7fb2492b"),
                            PricePerNight = 1500f
                        },
                        new
                        {
                            Id = new Guid("4b4c0ea5-0b9a-4a20-8ad9-77441fb912d2"),
                            Category = "Suite",
                            HotelId = new Guid("9461e08b-92d3-45da-b6b3-efc0cfcc4a3a"),
                            PricePerNight = 2000f
                        });
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = new Guid("c6c45f7c-2dfe-4c1e-9a9b-8b173c71b32c"),
                            Email = "johndoe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PasswordHash = "c6c45f7cprecomputed_hash_value",
                            PhoneNumber = "1234567890",
                            Role = "Guest",
                            Salt = "c6c45f7cprecomputed_salt_value"
                        },
                        new
                        {
                            Id = new Guid("aaf21a7d-8fc3-4c9f-8a8e-1eeec8dcd462"),
                            Email = "janesmith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PasswordHash = "aaf21a7dprecomputed_hash_value",
                            PhoneNumber = "0987654321",
                            Role = "Guest",
                            Salt = "aaf21a7dprecomputed_salt_value"
                        },
                        new
                        {
                            Id = new Guid("f44c3eb4-2c8a-4a77-a31b-04c4619aa15a"),
                            Email = "alicejohnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PasswordHash = "f44c3eb4precomputed_hash_value",
                            PhoneNumber = "1122334455",
                            Role = "Guest",
                            Salt = "f44c3eb4precomputed_salt_value"
                        });
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.Owner", b =>
                {
                    b.HasBaseType("TravelAccommodationBooking.Model.Entities.User.User");

                    b.HasDiscriminator().HasValue("Owner");

                    b.HasData(
                        new
                        {
                            Id = new Guid("55b1aa11-12e7-4e0f-8425-67c1c1e62c2d"),
                            Email = "raghadmohammad253@gmail.com",
                            FirstName = "Raghad",
                            LastName = "AbuSamor",
                            PasswordHash = "55b1aa11precomputed_hash_value",
                            PhoneNumber = "0595758383",
                            Role = "Admin",
                            Salt = "55b1aa11precomputed_salt_value"
                        },
                        new
                        {
                            Id = new Guid("77b2c30b-65d0-4ea7-8a5e-71e7c294f117"),
                            Email = "ayatalan@gmail.com",
                            FirstName = "Ayat",
                            LastName = "AbuAllam",
                            PasswordHash = "77b2c30bprecomputed_hash_value22",
                            PhoneNumber = "0595758382",
                            Role = "Admin",
                            Salt = "77b2c30precomputed_salt_value"
                        });
                });

            modelBuilder.Entity("RoomFeatureRoomType", b =>
                {
                    b.HasOne("TravelAccommodationBooking.Model.Entities.Rooms.RoomFeature", null)
                        .WithMany()
                        .HasForeignKey("FeaturesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAccommodationBooking.Model.Entities.Rooms.RoomType", null)
                        .WithMany()
                        .HasForeignKey("RoomTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.Booking", b =>
                {
                    b.HasOne("TravelAccommodationBooking.Model.Entities.Rooms.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAccommodationBooking.Model.Entities.User.User", null)
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.Discount", b =>
                {
                    b.HasOne("TravelAccommodationBooking.Model.Entities.Rooms.RoomType", null)
                        .WithMany("Discounts")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.Hotel", b =>
                {
                    b.HasOne("TravelAccommodationBooking.Model.Entities.Hotel.City", null)
                        .WithMany("Hotels")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelAccommodationBooking.Model.Entities.Hotel.Owner", null)
                        .WithMany("Hotels")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.Payment", b =>
                {
                    b.HasOne("TravelAccommodationBooking.Model.Entities.Hotel.Booking", null)
                        .WithOne("Payment")
                        .HasForeignKey("TravelAccommodationBooking.Model.Entities.Hotel.Payment", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.Review", b =>
                {
                    b.HasOne("TravelAccommodationBooking.Model.Entities.Hotel.Booking", null)
                        .WithOne("Review")
                        .HasForeignKey("TravelAccommodationBooking.Model.Entities.Hotel.Review", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Rooms.Room", b =>
                {
                    b.HasOne("TravelAccommodationBooking.Model.Entities.Rooms.RoomType", null)
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.Booking", b =>
                {
                    b.Navigation("Payment");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.City", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Rooms.RoomType", b =>
                {
                    b.Navigation("Discounts");
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.User.User", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("TravelAccommodationBooking.Model.Entities.Hotel.Owner", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
